### ISSUE TITLE
Align chat

### ISSUE THREAD

**Issue by ghost** [NikolayLiber/chatbro-wordpress#1]
How to align  "bottomLeft"?  sorry i don't know anything about it.

**Comment by andysavage** [comment]
In the settings, under default view > maximized chat > indents of maximized chat you can set the distance from the edges which can align it left or right, top or bottom. There's a preview so you can see what will happen.  Do the same for minimized chat, just below maximized.
![chatbro](https://user-images.githubusercontent.com/12832713/75091983-204cff00-556b-11ea-915b-bb636b4262d4.png)

**Comment by ghost** [comment]
> Nas configurações, em modo de exibição padrão> bate-papo maximizado> recuos do bate-papo maximizado, você pode definir a distância das bordas que podem alinhá-lo à esquerda ou à direita, em cima ou em baixo. Há uma visualização para que você possa ver o que vai acontecer. Faça o mesmo para o bate-papo minimizado, logo abaixo do maximizado.
> ![chatbro](https://user-images.githubusercontent.com/12832713/75091983-204cff00-556b-11ea-915b-bb636b4262d4.png)

Wow, I hadn't seen it, thank you very much

**Comment by ghost** [comment]
Ok :) I really hadn't seen it, now I managed to put the messenger and chatbro thanks
![Image](https://i.imgur.com/dRMBLaJ.jpg)
